### PR TITLE
Added bower install option

### PR DESCRIPTION
**Pull request by TriangleJuice**
Still needs to be registered: e.g. bower register randexp git://github.com/fent/randexp.js.git

### CODE REVIEW

**Comment by fent** [comment]
Thank you!

**Comment by TriangleJuice** [comment]
You're welcome!

**Comment by fent** [comment]
Wait hmm. I'm not sure I registered it correctly. After I ran `bower install randexp`, the downloaded folder doesn't include the build. I'm guessing because it's not in the repo.

**Comment by TriangleJuice** [comment]
Yeah… you'll need to release a new version (tag) in order to be picked up by Bower.

**Comment by fent** [comment]
Ah ok. New tag added and seems to be working. Thanks for the help.

**Comment by TriangleJuice** [comment]
Glad everything works now. Also thanks for the quick merge! :-)

**Pull request merged**
