### PR TITLE
Updated readme with RandomGenerator Example

### PR DESCRIPTION
**Pull request by rekaj3773**
Not sure if you're open to it include it, but I've added my little project based on randexp.js.
Hope I'm requesting correctly!

### CODE REVIEW

**Comment by fent** [comment]
I see that that repo is your first github project, and I don't mean to discourage you in your learning goals. But I think your project could be better represented as an example on the [randexp.js page](http://fent.github.io/randexp.js/).

**Comment by rekaj3773** [comment]
Absolutely.  It would be my great honor to have an addition there.  What can I do to help?

**Comment by fent** [comment]
Sorry, I missed seeing your response.

> What can I do to help?

You can add your regex to the list of examples

https://github.com/fent/randexp.js/blob/gh-pages/main.js#L11-L58

**Comment by rekaj3773** [comment]
Thanks for the direction!  I'll add it over there soon.  I'll suppose it's appropriate to revoke the pull request.  Let me know if you need anything else.

**Pull request closed without merging**
